### ISSUE TITLE
Macro library and text substitution feature request

### ISSUE THREAD

**Issue by SamWindell** [nojanath/SublimeKSP#1]
Really appreciate your work on this, and adding it PackageControl, I found it just by chance. I've recently put together a macro and function KSP library, which I think could be useful to you if you do scripting work. It's main feature is the addition of UI arrays and the ability to execute a macro a given number of times, kind of like a for-loop. You can find it on my github: https://github.com/SamWindell/KSEL

I have an idea for a feature request for SublimeKSP. Apologies if this is better suited to send to Nils direct, just wondering what you thought about it. 

A pre-compile text substitution would be really helpful. Kind of how the C preprocessor #define works. At the top of the document you could define some constants: 
```
#define NUM 1
#define TEXT string
```

Then when you hit F5 all occurrences of NUM or TEXT will just be replaced by their value, after this has happened, then the compiler proceeds and builds macros, functions, etc.

Especially in the pseudo arrays that I have made in my macro library, this feature would be really useful.

**Comment by nojanath** [comment]
Thanks for sharing your macro and function library.  That looks super helpful.

As for the feature request, that would be something for Nils directly.  I'm only planning incremental improvements with this fork for the moment.  Nothing major.  The main objective was to get this in Package Control and have up-to-date Kontakt support.

**Comment by SamWindell** [comment]
Ok, no worries. Thanks for your work.
