### ISSUE TITLE
Way to run iterate_macro alongside literate_macro?

### ISSUE THREAD

**Issue by magneto538** [nojanath/SublimeKSP#103]
I haven't thought a lot about this to be honest, but I was wondering if there is a way to run literate_macro and upon every new round have a constant incrementing. The way I am using to do it at the moment is

```
START_INC(N, 0, 1)
literate_macro( some_macro ) on LITERALS
END_INC
```

where N would be incremented by 1 when each macro is unrolled. `some_macro` contains a call to N of course.

I was wondering if there is a better way to do this and, if not, if something can be added to the compiler to be able to accomplish this.

**Comment by neblix** [comment]
Hey Davide,
  

  
I think the way you’ve done it is concise and flexible enough, making use of existing compuler features. With START_INC() you get all the power it offers like step size, start point, etc.
  

  
It’s bad practice to make a brand new language feature for every single little technique that comes up. It clutters the language and makes for poor extensibility down the road. (Ex. What if we changed START_INC() to improve it down the line? Your current technique would reap the benefit, a separate new technique would not.)
  

  
-Nabeel A.
  

  
  

  
  
>

**Comment by magneto538** [comment]
I'm totally fine with that and actually I like that solution as well. Was wondering if there were any other way to do it - I was misusing the "Issues" board actually, asking for opinions as if it were a forum. Sorry about that :)
