### ISSUE TITLE
Compile .ksp file from command line

### ISSUE THREAD

**Issue by franto** [nojanath/SublimeKSP#105]
Is it possible to use KSP compiler from command line? Sorry to ask this question via submitting new issue.

**Comment by blackeyedpony** [comment]
yes, just take a look at ksp_plugin.py  around line 151
https://github.com/nojanath/SublimeKSP/blob/master/ksp_plugin.py

**Comment by franto** [comment]
Thank you for you help. I found workaround using command line command
`subl --command "ksp_recompile" -b`, which works nicely. Only one thing is missing from my point of view. Output to stdin and stderr, otherwise I need to check SublimeText for compilation status and/or errors.

Btw. I'm using SublimeKSP for compiling KSP in IntelliJIdea, it works nicely. Thank you for your hard work guys!
