### ISSUE TITLE
USE_CODE_IF is no longer working when used outside macros

### ISSUE THREAD

**Issue by magneto538** [nojanath/SublimeKSP#108]
This used to work prior to the latest update, therefore some existing scripts could be broken. 
After the latest updates, which improved quite massively how SET_CONDITION and USE_CODE_IF work, USE_CODE_IF can no longer be used outside a macro. Although this behaviour makes sense, I'm afraid of backwards compatibility here.

**Comment by dxmachina** [comment]
This has broken a number of legacy scripts here as well.

**Comment by dxmachina** [comment]
Thank you, yes I rolled back to this end of May commit: 499d8b80c22702f415aa48e02b546cb869ab973b

**Comment by andreasOL16** [comment]
Is this still an issue? I noticed in the most recent master (1.6.3?) that USE_CODE_IF now can be used in a nested way (which I had wished for years ago). What was/is the issue with using it outside a macro?

**Comment by neblix** [comment]
The latest commit has now fixed issues surrounded USE_CODE_IF. The improved behavior that it can nest is retained.
