### ISSUE TITLE
No fancy "read_persistent_var" in SublimeKSP

### ISSUE THREAD

**Issue by neblix** [nojanath/SublimeKSP#11]
The new 
"declare pers"

Is pretty dope! My only complaint while it does make_persistent, it does not do "read_persistent_var". Is there any plan to have a similar shorthand for reading, or no? 

Especially for a ui control array, since it generates control names automatically, we'd be forced to use an iterate macro for reading persistent ui control values. It would be nice if we had an equal shorthand for reading like "read <variable>" or "read <control array>". So that reading persistent values is not this big task of writing extraction macros for different sets of controls.

**Comment by neblix** [comment]
Sorry those meant to say

"read pers [variable]" or "read pers ui_control [control array]"

**Comment by SamWindell** [comment]
That's a good idea! read_persistent_var() is less common now that we have the persistence_changed callback, but I'm sure this feature would be handy especially for developing for pre-Kontakt 5.5. I wonder if the syntax should be just a single word though. For example `pers` just makes it persistent, and `read` makes it persistent and read. That might make it just a little bit simpler.

**Comment by neblix** [comment]
Yes. We rarely develop for Kontakt 5.5.
