### ISSUE TITLE
Update get_voice_limit in ksp_builtins_data.py

### ISSUE THREAD

**Issue by dxmachina** [nojanath/SublimeKSP#112]
Line 769 should be: `get_voice_limit(<voice­type>):integer`

**Comment by neblix** [comment]
@mkruselj Has actually informed me that get_voice_limit() is not to be assigned to integer variables, and so this change should be reverted.

**Comment by mkruselj** [comment]
That's incorrect, get_voice_limit() doesn't need assigning to an integer variable, so there's no need for `:integer` here.

**Comment by neblix** [comment]
As @mkruselj said, that's incorrect.

**Comment by dxmachina** [comment]
Why? It does return a valid int that can be assigned to a variable or checked as a conditional. The only issue is that code won't compile in Sublime without the above requested change.

Let me put this another way... the code that I maintain for several Native Instruments libraries requires using it this way - and so I've been changing the builtins to support this for a few years. I'll keep doing so if necessary - but for my own sanity - why should this not properly compile when returning an int (as is working in KT)?

**Comment by neblix** [comment]
Okay, I have looked at the KSP Reference myself and seen what you are saying is obviously correct; perhaps EvilDragon got confused between get and set in an accidental momentary lapse. I will fix this in the repo again.

**Comment by mkruselj** [comment]
It compiled over here even without :integer set up.

From my understanding, you use :integer in builtins only if the command is supposed to be assigned to a variable, like async operations or play_note(). This is not necessarily the case with get_voice_count, though, as it's not an sync operation.

**Comment by neblix** [comment]
The KSP Reference uses it as an integer return concatenating it with strings for messaging.

Curiously, it was always used on a separate line using `& ...` so maybe that tripped you up and you thought it was alone on a new line as its own op!

**Comment by neblix** [comment]
Additionally, looking at builtins, the point that :integer is reserved exclusively for variable assignment as a restriction seems to be wrong; several of the functions denoted as :integer can be used in messages and conditionals, such as get_control_par().

**Comment by dxmachina** [comment]
Thank you.

The only way the function would compile was when it was used as a string (either messaged or concat as mentioned) - otherwise the SublimeKSP syntax checking catches it on compile (if you disable syntax checking it may compile since it bypasses type checking). So, the following wouldn't compile for instance:

```
if (get_voice_limit(NI_VL_TMPRO_HQ) > 4)
	message("I'm a pro!")
end if
```

My understanding was that the builtins was exactly the former you mentioned, pryzmusic, the expected return type. But I yield to those who've been working on the internals.
