### ISSUE TITLE
Optimize compile time by removing unused branches on macro expansion

### ISSUE THREAD

**Issue by blackeyedpony** [nojanath/SublimeKSP#118]
The compile time of projects making extensive use of macros containing conditions, which could be evaluated before parsing the code could be greatly improved when unused branches would be directly removed from the code after expand_macros().

**Comment by blackeyedpony** [comment]
Image you create many knobs with labels, which have slightly different functionality. Take a look at the macro "create_knob_callback". This can be very long with man customisations. All these get inserted in every macro expansion, which is not necessary and increases compile time. 

```
macro declare_knob(#v#,#id#,#expo#,#min#,#max#,#unit#)
	declare const #v#_id := #id#
	declare const ~#v#_exp := #expo#
	declare const #v#_min := #min#
	declare const #v#_max := #max#
	declare @#v#_unit := #unit#
	declare ~#v#_fl
	declare ui_knob #v#(#min#,#max#,1)
	declare ui_label #v#_label (0, 0)
	declare #v#_ui_ids[] := (get_ui_id(#v#),get_ui_id(#v#_label))
	for i := 0 to #v#_ui_ids.SIZE-1
		set_bounds(#v#_ui_ids[i], 100+100*#id#, i*50) 
	end for
end macro

on init 
	declare i
	set_ui_height_px(100)
	declare_knob(Linear,0,1.0,0,100,"%")
	declare_knob(Exponential,1,2.0,0,15000,"Hz")
end on

macro create_knob_callback(#v#)
	on ui_control (#v#)
		#v#_fl := int_to_real(#v#)/int_to_real(#v#_max)

		if #v#_exp # 1.0	// #v#_exp is a constant and the expression could be evaluated and the code block eventually be removed on macro expansion
			#v#_fl := pow(#v#_fl,#v#_exp)
			// image more code here
		end if

		if #v#_id = Linear_id	// #v#_id is a constant and the expression could be evaluated and the code block eventually be removed on macro expansion
			message("Linear")
			// image more code here
		end if

		#v#_label -> text := round(#v#_fl*int_to_real(#v#_max)) & " " & #v#_unit
	end on
end macro

literate_macro(create_knob_callback) on Linear,Exponential

```

**Comment by pryzmusic** [comment]
In the case I wouldn’t request a language feature for something that can be solved with better programming practices. Indulging in macro text-replacement is not a good way to write larger scale code.

You should use an array of parameters for your control data that can store all your argument data “constants” in (a separate array for other data types like floats and strings). Then you can simply turn your ui callback into a callable function.

This will significantly reduce your line count (and thus compile time) far more than removing unused conditionals, as each of your callbacks will simply set the index variable of your control (maybe #v_id# ?) and then call the function which contains your necessary code in just one place.

**Comment by pryzmusic** [comment]
We already have conditional code  removal using the commands `USE_CODE_IF()`.

**Comment by magneto538** [comment]
We cannot pass parameters to USE_CODE_IF as far as I know.

**Comment by pryzmusic** [comment]
I see what you're saying about the workflow for not declaring unnecessary data but please consider that SublimeKSP is a language extension, it's not an ever-expanding set of automation tools. If you have specific automation needs for your projects, like the ability to call control commands that conditionally paste subsections of its code, I recommend building your own tool for this. The least I can promise is to, eventually, roll out the ability to write your own private plugins that inject behaviors into the SublimeKSP compilation stages.

**Comment by magneto538** [comment]
Sounds fair. However, I think that what the OP was suggesting was to
explore a way to reduce compilation time in a real world scenario, not
adding features or automation tools. I think that anything that could
improve the existing codebase - which, as good as it is, can be improved
for sure in regards to compilation time - would be worth exploring, if
there's any chance to address the issue. My example was just one of the
cases where what the OP suggested would be useful.
We all appreciate your hard work on this and - since we are all working
with this tool - it's in our best interest, as developers, to provide
suggestions.

**Comment by pryzmusic** [comment]
2 things:

1. Inspecting the code base, there seems to be a compiler feature set in place for unused branches, but it somehow is a misnomer, as it does not remove unused branches due to expressions evaluating to a false conditional (like 1=0 for example). I can investigate how to modify it to achieve this.

2. Even with this fix, the compilation time will largely be unaffected. Simplifying expressions, and compiled output optimization happen in the latter stages of the compilation. Observe:

```            tasks = [
                 ('scanning and importing code', lambda: self.do_imports_and_convert_to_line_objects(),                       True,      1),
                 # NOTE(Sam): Call the pre-macro section of the preprocessor
                 ('pre-macro processes',         lambda: pre_macro_functions(self.lines),                  True,      1),
                 ('parsing macros',              lambda: self.extract_macros(),                  True,      1),
                 ('expanding macros',            lambda: self.expand_macros(),                                                True,      1),
                 # NOTE(Sam): Call the post-macro section of the preprocessor
                 ('post-macro processes',        lambda: post_macro_functions(self.lines),                 True,      1),
                 # NOTE(Sam): Convert the lines to a block in a separate function
                 ('convert lines to code block', lambda: self.convert_lines_to_code(),                                         True,      1),
                 ('parse code',                  lambda: self.parse_code(),                                                   True,      1),
                 ('various tasks',               lambda: ASTModifierFixReferencesAndFamilies(self.module, self.lines),        True,      1),
                 ('add variable name prefixes',  lambda: ASTModifierFixPrefixesIncludingLocalVars(self.module),               True,      1),
                 ('inline functions',            lambda: ASTModifierFunctionExpander(self.module),                            True,      1),
                 ('handle taskfunc',             lambda: ASTModifierTaskfuncFunctionHandler(self.module),                     True,      1),
                 ('handle local variables',      lambda: self.sort_functions_and_insert_local_variables_into_on_init(),       True,      1),
                 ('add variable name prefixes',  lambda: ASTModifierFixPrefixesAndFixControlPars(self.module),                True,      1),
                 ('convert dots to underscore',  lambda: self.convert_dots_to_double_underscore(),                            True,      1),
                 ('init extra syntax checks',    lambda: self.init_extra_syntax_checks(),                                     do_extra,  1),
                 ('check types',                 lambda: comp_extras.ASTVisitorDetermineExpressionTypes(self.module),         do_extra,  1),
                 ('check types',                 lambda: comp_extras.ASTVisitorCheckStatementExprTypes(self.module),          do_extra,  1),
                 ('check declarations',          lambda: comp_extras.ASTVisitorCheckDeclarations(self.module),                do_extra,  1),
                 ('simplying expressions',       lambda: comp_extras.ASTModifierSimplifyExpressions(self.module, True),       do_optim,  1),
                 ('removing unused branches',    lambda: comp_extras.ASTModifierRemoveUnusedBranches(self.module),            do_optim,  1),
                 ('removing unused functions',   lambda: comp_extras.ASTVisitorFindUsedFunctions(self.module, used_functions),      do_optim, 1),
                 ('removing unused functions',   lambda: comp_extras.ASTModifierRemoveUnusedFunctions(self.module, used_functions), do_optim, 1),
                 ('removing unused variables',   lambda: comp_extras.ASTVisitorFindUsedVariables(self.module, used_variables),      do_optim, 1),
                 ('removing unused variables',   lambda: comp_extras.ASTModifierRemoveUnusedVariables(self.module, used_variables), do_optim, 1),
                 ('checking empty if-stmts',     lambda: comp_extras.ASTVisitorCheckNoEmptyIfCaseStatements(self.module),     self.check_empty_compound_statements, 1),
                 ('compact variable names',      self.compact_names,                                                          self.compactVars, 1),
                 ('generate code',               self.generate_compiled_code,                                                 True,      1),
            ]```

To reiterate my point on programming practices, large-scale macro expansion is a huge time sink for the compiler, and by nature of how the code works, removing unused conditionals happening at the end stages of the compiler is cleaning up the code line count, but not actually improving parse times for any of the other compilation tasks which take more time. This is because all those tasks have already been run on the expanded codebase before the "clean-up" is set to occur.

I still recommend reducing reliance on macros for non-trivial code generation tasks and building homegrown tools instead if compilation time is a concern, because modifying the compiler will not grant any time savings. I will consider this issue a bug because the compiler design implies it is set up to remove these branches, even though it does not.

**Comment by pryzmusic** [comment]
Hey guys,

@magneto538 @blackeyedpony 

I had assumed if this was a reported issue that it would be accurate, however I am running the compilation on a very simple code example:

```
on init
	if(0=1)
		message(5)
	end if
end on

```

And the compiler is correctly removing the branch. I am not sure I understand the problem here?

**Comment by pryzmusic** [comment]
If the request is *merely* to move the optimization process towards after the code parsing process, this is **impossible**. The code HAS to be parsed before it can be simplified and optimized. The steps leading up to the compiler stages of simplifying expressions and removing unused code prepare the code and formats it into data structures of statement nodes that the latter stages of compilation rely on.

**Comment by blackeyedpony** [comment]
The idea was to perform a quick parsing per expanded macro and remove unnecessary code. Then run the normal compile process.

**Comment by pryzmusic** [comment]
I understand, but that's not feasible. The code has to be parsed according to the compiler model to format it into the right data structures before the optimization code can be run.

You can't do a "quick parsing". Parsing has to be very strict and robust.

**Comment by pryzmusic** [comment]
For example, a latter code conversion step deals with dots to underscores, which is a necessary component that has to run before simplifying expressions (simplifying expressions is required for any unused code cleanup).

**Comment by blackeyedpony** [comment]
Thanks for the exchange on this request. Closing...
