### ISSUE TITLE
Feature request: /* */ to make comments more in line with the new // single line comment

### ISSUE THREAD

**Issue by benjaminstelzer** [nojanath/SublimeKSP#123]
It would be great if we could have /* and */ additional to (* and *) to make comments look better in combination with the new single line comment //. Since I often switch between JS and KSP it also comes in handy to have the more similar syntax ;)

**Comment by mkruselj** [comment]
This is pretty easy to add, if I understand correctly it just needs updating regex to .sublime-syntax and to the ksp-compiler.py.

Will propose a pull request.
