### ISSUE TITLE
New Comment Style Parsing Corrupts KSP String Literals With URLS

### ISSUE THREAD

**Issue by neblix** [nojanath/SublimeKSP#13]
Hey Sam,

`set_control_par_str($INST_LIB_DESCRIPTION_ID, $CONTROL_PAR_TEXTLINE, "http://ocremix.org/")`

This line gives me trouble compiling. The compilation seems to get hung up on the string "http:"
![image](https://cloud.githubusercontent.com/assets/2980471/15525194/06fd430e-21f6-11e6-930d-e3731394679d.png)

Additionally the compilation of this script started hanging on "post-processing (15%)" at the bottom and the entire application froze up for a few seconds.

**Comment by neblix** [comment]
It seems like your comment parsing "//" reaches too far into strings; perhaps enhance the regex to make sure it is not within a quoted string?

**Comment by SamWindell** [comment]
Thanks for the info. You are correct, this seems to be that it is incorrectly finding a comment in the middle of the string. I don't think that this can be done with a single regex, multiple regexs will have to be combined perhaps. We just need to match all occurances of // to the end of the line that are not comments. Any suggestions would be great!

**Comment by SamWindell** [comment]
I must admit I don't recognise the "post-processing" message. I doubt this is related to the comments. Do you have any more info on this?

**Comment by neblix** [comment]
If nothing else, add the ability to disable // comments, perhaps? This would give you more time to work on it until you have a fix.

**Comment by neblix** [comment]
Sorry, I read the email and not the updated reply; thanks for the fix!

**Comment by SamWindell** [comment]
No problem! You can download the fixed version manually from this repo, if you need it now.

**Comment by neblix** [comment]
Is there an easy way to swap around versions of the plugin?

**Comment by SamWindell** [comment]
Not particularly easy, but in your sublime packages folder you could create different versions in different folders. Then in sublime use ctrl+shift+p to enable or disable the versions you want. If you have any more issues of old scripts not compiling let me know, backwards compatibility is important.

**Comment by nojanath** [comment]
Fixed in 1.3.3 which will be available in Package Control shortly.
