### ISSUE TITLE
Compiling does not work anymore

### ISSUE THREAD

**Issue by keman91** [nojanath/SublimeKSP#135]
After updating to 1.8.0 compiling does not work sometimes, depending on the file (?). No error message is shown and no code is copied into the clipboard. Had to downgrade back to 1.7.1 and everything is fine.

**Comment by pryzmusic** [comment]
Can you show me an example file that causes this issue?

**Comment by pryzmusic** [comment]
@keman91 Can you try uninstalling and reinstalling 1.8.0 using Package Control? This solved the issue for me.

**Comment by pryzmusic** [comment]
The issue has been fixed in version 1.8.1.
