### ISSUE TITLE
Automatic array size with // comments won't compile

### ISSUE THREAD

**Issue by clearfrost** [nojanath/SublimeKSP#138]
Automatic arrays with comments inside using the // style won't compile, have to use {}. Add the number of elements, and it does compile. 

Not a bit problem but can cause hours of frustration until you find it. Comments in arrays? Yes, in large multi-line matrix-like arrays with columns and rows.

**Comment by mkruselj** [comment]
I would really argue to use {} comments there because those are delimiting from both sides, whereas // comments delimit only on the left side, essentially eating the rest of your array then.

**Comment by clearfrost** [comment]
I used this as a column header only on its own line with ... at the end. I just wanted to bring it up as it was very frustrating because the compiler doesn't explain what the problem was. Doubt it will be changed but maybe a mention in the wiki to not use // anywhere in an array maybe will save someone else some frustration, that's all really.

**Comment by mkruselj** [comment]
Added a mention to the wiki about this!

**Comment by mkruselj** [comment]
Also:

![image](https://user-images.githubusercontent.com/2393720/78838804-3d447100-79f7-11ea-9b3c-fafd719def5a.png)

This actually works! So there seems to be no issue. It won't work if you used your // style comment _before_ the ellipsis ...

**Comment by pryzmusic** [comment]
Any code to the right of the `//` is commented, that's what `//` comments are for. If you want code to be understood after a comment on the same line you would use a closed comment like `{ }` or `/* */`.
