### ISSUE TITLE
Unused string variables and arrays not removed with optimize code

### ISSUE THREAD

**Issue by clearfrost** [nojanath/SublimeKSP#139]
Unused string variables and arrays not removed with optimize code.

Why don't I remove them? Same script imported into different slots. Get around it with SET_CONDITION and USE_CODE_IF but would be nice not to have to.

**Comment by mkruselj** [comment]
I cannot confirm this.

```
on init
	declare !array[5]
	declare @str
end on

{ Compiled on Thu Oct 24 17:51:33 2019 }
on init
end on
```

**Comment by clearfrost** [comment]
Sorry, I meant initialised variables.

**Comment by mkruselj** [comment]
If variables have an initial value defined, they are considered as used already.
