### ISSUE TITLE
More visible 'Successfuly compiled' message

### ISSUE THREAD

**Issue by JosepBernad** [nojanath/SublimeKSP#148]
First of all, thanks for this amazing tool. I've been scripting for just a few months and I'm doing really complex and tricky scripts to get the best out of the instruments, and this library has a lot to do with it.

Let me give you some context for this request.
I'm currently working with a few big libraries, and the compilation time in some of them is noticeably long (2-3 min). What I usually do is to work in other stuff while is compiling, but sometimes I'm not sure if it's compiled or not, because the message in the bottom of Sublime Text disappears within a few seconds.

Is there any other way to show the message?

Thnaks again!

**Comment by mkruselj** [comment]
There is an audio that should be played when compilation is done. Inside SublimeKSP add-on folder, there is a "sounds" subfolder, which is supposed to have "finished.wav" and "error.wav" files in there. Do you not have them? If you don't, update SublimeKSP to latest version.
