### ISSUE TITLE
Enter key fails to work after installing an autocomplete fix

### ISSUE THREAD

**Issue by iGitErDone** [nojanath/SublimeKSP#149]
https://forum.sublimetext.com/t/ksp-sublime-kontakt-script-processor-plugin/48682/3

At the above link, OdatNurd provides a fix for the autocomplete issues in KSP, namely that autocomplete does not work when the Kontakt scripting variable prefix characters '$' and "~" are the trigger.

This fix works perfectly until I close and then restart Sublime. After restarting, the triggers still work and autocomplete correctly but the enter key no longer generates a new line. This seems to happen when no ksp source was open for editing when Sublime was closed.

I could find nothing amiss in the OverrideAudit reports.

Here’s what I get in the console when I log inputs and commands
key evt: enter
command: ksp_on_enter

The ksp_on_enter command does nothing. I have not been able to trace the issue any further.

**Comment by iGitErDone** [comment]
OdatNurd posted a solution to this enter key issue on the Sublimetext forum. Here is the link to that solution:
https://forum.sublimetext.com/t/ksp-sublime-kontakt-script-processor-plugin/48682/8

If you incorporate the two posts by OdatNurd on this issue in that forum you will have a fully functioning autocomplete capability in KSP Sublime.

**Comment by pryzmusic** [comment]
Closed by mistake.

**Comment by pryzmusic** [comment]
This has now actually been fixed!
