### ISSUE TITLE
Syntax highlighting bug

### ISSUE THREAD

**Issue by SamWindell** [nojanath/SublimeKSP#15]
Great work with the new syntax highlighting file. This is clearly a much nicer system.

However, for me any regex matches in the sublime-syntax file that spanned multiple lines were not read properly. As a quick fix I have made them all single lines. This seems to have done the trick for me.

**Comment by nojanath** [comment]
That's what I get for testing this late at night.  I'll push that out shortly.

**Comment by nojanath** [comment]
1.3.4 tagged.  Package control will pull it in an hour or so.
