### ISSUE TITLE
1.9.2: importing as namespaces is broken

### ISSUE THREAD

**Issue by mkruselj** [nojanath/SublimeKSP#156]
import.ksp:
```
macro do_init()
	declare i := 5
end macro
```

main.ksp:
```
import "import.ksp" as foo

on init
	foo.do_init()
	message(foo.i)
end on
```

This results in an error message:

![image](https://user-images.githubusercontent.com/2393720/79039993-89ed9f00-7be5-11ea-98ea-8a1501eba787.png)

Reported by Mickaël Le Goff.

**Comment by pryzmusic** [comment]
This has been fixed in 1.9.3.
