### ISSUE TITLE
{} comments break (*) blocks

### ISSUE THREAD

**Issue by sonthomsen** [nojanath/SublimeKSP#160]
if you want to quickly comment out a block of code with descriptive comments inside of it that seems no longer possible

**Comment by pryzmusic** [comment]
Hi sonthomsen, I somehow missed this. Can you verify this happens in 1.9.11 and post an example of code that breaks?

**Comment by sonthomsen** [comment]
Hi Nabeel,

I just synced git and tried and it seems that the code now compiles, although it still looks wrong - here's the same code using your distribution, and the other one we reverted back to.

Son

**Comment by pryzmusic** [comment]
Hi,
Did you forget to include the code here? I don’t see it!

**Comment by mkruselj** [comment]
@pryzmusic So this seems to work just fine, but syntax coloring goes awry.

```on init
    (* 
        this is an example comment inside a comment!

        {
            foobar
        }
    *)

    message("")
end on
```

And it colors like this:

![image](https://user-images.githubusercontent.com/2393720/139683260-c4162c93-9881-4775-a56a-b9ba2b3ade1c.png)

**Comment by mkruselj** [comment]
This is going to be fixed in the next update, thanks to the helpful comment from [jfcherng back at Sublime Text forums](https://forum.sublimetext.com/t/help-with-syntax-definition-coloring/63433/2)!
