### ISSUE TITLE
feature request: postcompile remove block or pseudo declaration

### ISSUE THREAD

**Issue by andreashe** [nojanath/SublimeKSP#161]
There is a problem using load_performance_view(), because it does declarations by itself. But in Sublime compiler it requires the declarations of UI elements.

My  feature request would be to make something like
// POSTCOMPILE_REMOVE_START
declare $knob
// POSTCOMPILE_REMOVE_END

which removes that before copying to clipboard.

Alternatively a way to pseudo declare e.g. a $knob, so the compiler assumes a declaration, even if there is none.

**Comment by pryzmusic** [comment]
This feature is already handled by SublimeKSP. You have to use the `import_nckp()` command, which takes a filepath to your nckp file.

**Comment by andreashe** [comment]
Wow, so quick! Yes! It works! I went over this in the documentation but I did not sound to me like the solution. By the way, there is a tiny typo if the file is not found, it tells a "nkcp file not found". I think it is "nckp".
