### ISSUE TITLE
"and" and "or" operators in USE_CODE_IF

### ISSUE THREAD

**Issue by willbedford** [nojanath/SublimeKSP#168]
Allow use of multiple conditions inside USE_CODE_IF and USE_CODE_IF_NOT.
For example,
`USE_CODE_IF((CONDITION_1 and CONDITION_2) or CONDITION_3)`

**Comment by pryzmusic** [comment]
This would be very difficult for me to implement as it would mean having expression parsing inside USE_CODE_IF, which currently is not there at all, and there are no compiler data classes that support the SET_CONDITION usages, so I'd be basically writing an expression parse from scratch. I'll try to look at this if I get to your other request.
