### ISSUE TITLE
USE_CODE_ELSE

### ISSUE THREAD

**Issue by willbedford** [nojanath/SublimeKSP#169]
```
USE_CODE_IF(CONDITION)
	//stuff
USE_CODE_ELSE
	//more stuff
END_USE_CODE
```
would be shorthand for 
```
USE_CODE_IF(CONDITION)
	//stuff
END_USE_CODE

USE_CODE_IF_NOT(CONDITION)
	//more stuff
END_USE_CODE
```

**Comment by willbedford** [comment]
also USE_CODE_ELSE_IF()

**Comment by pryzmusic** [comment]
I don't think this would be impossible but it would add some new stuff the current loop for this basically doesn't have. I'll see what I can do the next time I work on features.
