### ISSUE TITLE
Macro prints wrong string

### ISSUE THREAD

**Issue by scrugbuttocks** [nojanath/SublimeKSP#174]
One of my simple help text functions is outputting the wrong string....

When I compile it and then hover over that control in Kontakt it outputs "stereo 350"

macro view.layer.block(#side#, x, y, width, height, mouse)

    family layers

          view.layers.slider(stereo_width_#side#, "", x + $x_off * 2 + $x_off_dist, y + $y_off_top, 500000, 1000000, 500000, mouse)
   
        layers.sli_stereo_width_#side# -> HELP := "stereo width"  

    end family      
end macro

Apologies, I don't know how to format code in github properly. First post

**Comment by pryzmusic** [comment]
There is too little information in this issue to investigate anything. Try posting a self-contained ksp file that has the issue, or paste the compiled txt file of the script.

**Comment by scrugbuttocks** [comment]
[tab_1_controller.zip](https://github.com/nojanath/SublimeKSP/files/5542135/tab_1_controller.zip)

Here's a zip with the code included. Thank you for taking the time!

**Comment by pryzmusic** [comment]
This doesn't help; this code relies on some ui library you have written in order to compile.

I can not debug compiler issues on files I can not compile, so please provide a self-contained code file that has the issue, or just provide the final compiled txt result so I can see what was compiled.

**Comment by scrugbuttocks** [comment]
[tab_1.txt](https://github.com/nojanath/SublimeKSP/files/5542238/tab_1.txt)
Better?

**Comment by pryzmusic** [comment]
I see the problem now, notice where 350 shows up multiple times. "Width" is your macro argument, so it is being replaced wherever it shows up.

Make sure all macro arguments are surrounded by the # sign, so `#side#, #x#, #y#, #width#, #height#, #mouse#` and not `#side#, x, y, width, height, mouse`. The latter is not supported and shouldn't be used at all.

**Comment by scrugbuttocks** [comment]
Ok, I still don't exactly understand why it happened and not using the # has been working fine for 3000 lines of code, but I guess I'll just accept it.
I'll try your recommended method of replacing!

**Comment by pryzmusic** [comment]
Hi,

As I explained, `width` is an argument in your macro. When you supply the number 350 for your width, then in the string where you type "stereo width", it replaces `width` with 350 to print "stereo 350".
