### ISSUE TITLE
Req: From X to Y shorthand

### ISSUE THREAD

**Issue by ericchesek** [nojanath/SublimeKSP#182]
I would like to be able to create lists of values using some kind of shorthand similar to the following code.
`declare MyList[] := (1::10)` 
which would replace the need to type out (1,2,3,4,5,6,7,8,9,10).

Creating lists of Kontakt groups gets time consuming when typing out each number, so this would be a very nice way to speed up the process! 

Thanks for the consideration.
-Eric

**Comment by pryzmusic** [comment]
I'm not sure I understand. What is the purpose of creating an array of just a regular incrementing sequence of numbers? The array you just created, for example, doesn't need to be an array, it's just the equation "x + 1" where x is your array index.

**Comment by pryzmusic** [comment]
Here is a quick macro I created that allows you to create a list from a "min" to a "max", even providing a spacer value if the increment isn't just 1. You only need to make sure "i" and "j" are declared in your init callback.

```macro CreateList(#name#, #min#, #max#, #step#)
    declare #name#[(#max# - #min#)/#step# + 1]
    i := #min#
    j := 0
    while(i <= #max#)
        #name#[j] := i
        i := i + #step#
        inc(j)
    end while
end macro```

Example usage: `CreateList(MyList, 0, 20, 4)` which creates an array as (0, 4, 8, 12, 16, 20).

I encourage you to learn how to utilize the tools we already have in the compiler!

**Comment by ericchesek** [comment]
Okay, that certainly does the job! I tried something similar with a macro but got stuck when trying to make concatenations work. This is a much better solution. Thanks.
