### ISSUE TITLE
Sublime 4.4126 introduced a weird bug for imported ksp files within the code

### ISSUE THREAD

**Issue by gabrieldib** [nojanath/SublimeKSP#188]
I tested this multiple times:
Say I have a main.ksp and a functions.ksp files and I am importing the functions.ksp file in the main via import "functions.ksp". Whenever I change something in the functions.ksp file, save it and try to compile the main.ksp, it will act as if the functions.ksp was never changed and saved, as if there is a buffer of the last imported file. 
It seems to run ok if I restart sublime. But imagine me closing and opening Sublime everytime I save an external ksp file... ugh.

on a Mac 10.14

**Comment by gabrieldib** [comment]
uninstalling and installing the plugin sovled this.

**Comment by gabrieldib** [comment]
Actually, sorry for the confusion - NO, it this issue was NOT resolved by reinstalling the plugin. It is still happening.

**Comment by pryzmusic** [comment]
Perhaps we’ll see if Sublime patches this in a newer version since I imagine it’s likely broken other plugins too.

The folks who wrote the Sublime integration don’t maintain this repo anymore, and I’m not sure how any of that stuff works. I really just approve additions of new KSP syntax as NI rolls it out.

In the meantime, I recommend just rolling back the Sublime version.

**Comment by gabrieldib** [comment]
wow thank you so much for replying so fast on a xmas eve, impressive.
I tried finding build 4121, will look a little harder.
Thanks.

**Comment by gabrieldib** [comment]
I did roll back to 4121 and problem was not solved. 
Then rolled back to Sublime Text 3. Also not solved. 

Any ideas?

**Comment by gabrieldib** [comment]
Actually, solved.
I accidentally had another copy of the same sublime project window opened, with all the ksps in tabs another folder on the side bar. Probably the plugin was getting confused.
