### ISSUE TITLE
Pinging nojanath!

### ISSUE THREAD

**Issue by mkruselj** [nojanath/SublimeKSP#193]
Hello @nojanath!

I’m Mario, also known as EvilDragon online, and I have been deeply involved with Kontakt scripting and SublimeKSP ever since it was conceived.

A long time ago (I reckon somewhere around 2016 or so), Nabeel Ansari from Impact Soundworks (eitherys on GitHub) asked you for access to the repository in order to be able to merge pull requests and create releases. This worked well up to a point, but Nabeel is becoming busier and busier these days, so they aren't always available to do these things.

I would be happy to continue maintaining this repository with fresh updates (especially since I am actually also involved in developing Kontakt itself these days!), so if this @ mention finds you well, I kindly ask you to grant me required access to SublimeKSP repository.

Thank you very much, and wish you all the best!

~Mario

**Comment by nojanath** [comment]
Hi Mario! Glad to see that you're involved with this and keeping it going. I'd be happy to grant you the required access. I just sent you a collaborator invitation. If you have any issues, please let me know!

Cheers,

JT

**Comment by mkruselj** [comment]
Awesome! That was fast (and perhaps I should've @ you sooner, hehe). Thanks!

Happy days! 🙂
