### ISSUE TITLE
KEY_COLOR_FUCHSIA not defined

### ISSUE THREAD

**Issue by neblix** [nojanath/SublimeKSP#20]
Hey guys!

We're doing some keyswitch coloring, but KEY_COLOR_FUCHSIA (added in 5.5) is popping up errors in the compiler.

**Comment by nojanath** [comment]
Can you provide an example?  I'm not able to repro that.  KEY_COLOR_FUCHSIA is defined in ksp_builtins_data.py - https://github.com/nojanath/SublimeKSP/blob/master/ksp_compiler3/ksp_builtins_data.py#L433.  

Perhaps the original SublimeKSP plugin is still active?

**Comment by neblix** [comment]
Let me ask my coworker, then. We thought we removed all traces of it. Perhaps he also just misspelled it... Fuchsia's a tough color. ;)

**Comment by neblix** [comment]
It turns out my coworker was unable to compile it because he indeed misspell it. Apologies!
