### ISSUE TITLE
iterate/literate on nothing causes crash

### ISSUE THREAD

**Issue by Reid115** [nojanath/SublimeKSP#200]
If you write...

`literate_macro(some_macro)`

...instead of...

`literate_macro(some_macro) on something`

...the compiler will abruptly stop running at 13% (when it processes macros), and no error will show. The next time you run the compiler, Sublime will freeze/crash. This applies to both iterate and literate. Obviously this is a user mistake, but it should probably give a syntax error instead of the current behavior. Thanks.

**Comment by mkruselj** [comment]
Nice catch, thanks for reporting!

**Comment by mkruselj** [comment]
Found the cause and managed to fix. Next version of SublimeKSP will contain it!
