### ISSUE TITLE
This is my unlucky day.

### ISSUE THREAD

**Issue by Reid115** [nojanath/SublimeKSP#205]
![Clipboard01](https://user-images.githubusercontent.com/103473356/170893135-cc0a1b61-22d7-4ffc-818d-2f7fb27ac8d4.png)

I just started getting this exception when I try to compile. It looks like the same compact name was given to two variables. Why not just generate another compact name if it finds it already exists? Thanks.

**Comment by mkruselj** [comment]
Closing this one since obfuscator should probably be not touched, ever. 😅
