### ISSUE TITLE
Logger does not work across imports using namespaces

### ISSUE THREAD

**Issue by rd778** [nojanath/SublimeKSP#208]
Hello! 

If you activate the logger (activate_logger) then use print(), Sublime displays an error message when compiling if you are using the logger across different namespaces. 

For example, this quick test:

### FILE 1
```
import "engine.ksp" as engine

on init
	activate_logger("C:/Log File.nka")
	print("hello")

	engine.doInit()

	engine.test()

end on
```

### FILE 2 (engine.ksp)
```
macro doInit()

	print("y")

end macro


function test()

	print ("hey")
	
end function
```

When compiling, the result is: "engine.print has not been declared". 

Why this is an issue: As the activate_logger and print() functions are within Sublime KSP and not local functions to the individual imported files, I'd expect these to act globally and not be affected by any namespaces. The logger is a handy tool but can't be used when working across large projects with multiple files imported as namespaces.

**Comment by mkruselj** [comment]
I am closing this issue, since with the upcoming 1.14 version of SublimeKSP we will deprecate the logger, and in version 1.15 we will completely remove it.
