### ISSUE TITLE
Compiler adds a space after declare ui parentheses

### ISSUE THREAD

**Issue by Reid115** [nojanath/SublimeKSP#209]
For some reason the compiler adds 1 space after the parentheses of a ui element declaration. This does not occur for element declarations that do not involve parentheses (e.g., ui_menu) or declarations that aren't ui elements. Not really a bug, but I can't see why an unneeded character should be there every time.

![image](https://user-images.githubusercontent.com/103473356/185721456-31fc2f1d-a44e-436b-bbd0-fba112dbb4ea.png)

**Comment by mkruselj** [comment]
Absolutely agreed, and this is an easy fix. The only reason why I haven't done this is that it would create a decent amount of noise in Git diffs (for those companies which use Git for version control of their scripts)...
