### ISSUE TITLE
How to use activate_logger on Mac?

### ISSUE THREAD

**Issue by dxmachina** [nojanath/SublimeKSP#21]
Trying to test your debugging function... the compiler won't accept Mac OS directory, like

activate_logger("/Users/me/Desktop/Log File.nka")

Is there a syntactic workaround? If I edit the appropriate line in the compiled code to Mac OS format it does work.

**Comment by SamWindell** [comment]
Thanks for the info, the syntax checking for the filepath was too strict for Mac. I have fixed this now, you can download manually from here, or if not the fix will be in the next update through package control.

**Comment by dxmachina** [comment]
Working nicely... thanks!
