### ISSUE TITLE
taskfunc -> return and out params don't work correctly

### ISSUE THREAD

**Issue by Reid115** [nojanath/SublimeKSP#217]
The TCM manual states that, when calling taskfuncs that have a return value, assigning that value to something is optional. However, if you don't assign it to something, for some reason none of the parameters in the call will be read (and they will all be set to 0). Example:

```
on init
    message("")
    tcm.init(1000)
    declare ui_switch swch
    declare i
    declare val
end on

taskfunc tf(num) -> return
    message(num)
    return := 456
end taskfunc

on ui_control (swch)
    //i := tf(123)
    tf(123)
end on
```

When you click the switch, it will print out "0". If you replace the tf call line with the line above it that sets the return value to i, you will see the correct "123" printed out.

Another problem is with out parameters. I could be wrong, but I assume that out params are supposed to be initialized to zero. But they're actually remembering whatever the ending value was the last time the taskfunc was called. Example:

```
on init
    message("")
    tcm.init(1000)
    declare ui_switch swch
    declare val
end on

taskfunc tf(out return) // return does NOT reinitialize to 0
    inc(return)
end taskfunc

on ui_control (swch)
    val := 0 // not necessary, just whittling down the problem
    tf(val)
    message(val)
end on
```
If you press the switch again and again, the numbers being printed out will be 1, 2, 3, 4, 5, etc... whereas it should keep printing out 1. Perhaps out params are only supposed to be assigned to, I'm not sure.

**Comment by Reid115** [comment]
I dug into the return issue a little further and basically this is what the compiled code looks like:
```
function tf
%p[$sp-3] := $fp
$fp := $sp-3
$sp := $fp
message(%p[$fp+1])
%p[$fp+2] := 456
$sp := $fp
$fp := %p[$fp]
$sp := $sp+3
end function

// the CB that assigns the return
on ui_control($swch)
%p[$sp-2] := 123
call tf
$i := %p[$sp-1]
end on

// the CB that doesn't assign the return
on ui_control($swch)
%p[$sp-1] := 123 // should be sp - 2, not sp - 1
call tf
end on
```
The tf function is the same for both, it's just the caller that changes. Essentially what is happening is that 2 spots in the frame are being allocated -- first, one spot (sp - 1) for the return value, and second, one spot (sp - 2) for the argument. In the CB that doesn't assign the return value, it thinks "oh I don't need two slots because I don't care about the return value, I just need 1 slot for the argument", so it puts the argument in sp - 1 instead of sp - 2. But the function doesn't mimic this behavior, and still tries to read the argument from sp - 2, thus getting a 0 because nothing was put there. So the solution is to ensure that the structure of the frame doesn't change, and a spot for the return value is still allocated, regardless if it will end up being used. Not sure what would need to change in the repository for that to happen.

**Comment by mkruselj** [comment]
As for the other issue you outlined, I am inclined to agree with your assumption:

> Perhaps out params are only supposed to be assigned to, I'm not sure.

Yeah they are only supposed to be assigned to. `out` parameters are basically just a way to have multiple return values.
