### ISSUE TITLE
override without base function

### ISSUE THREAD

**Issue by andreasOL16** [nojanath/SublimeKSP#221]
This is compiled

`on init
end on

function func override
	message("func overriden without base function")
end function

on note
	call func
end on
`

I would expect the compiler to complain about the override keyword.

**Comment by mkruselj** [comment]
File ksp_compiler.py, line 689 onwards. See if something could be done there?

**Comment by mkruselj** [comment]
Looking into it more with @JackWilliams-FractureSounds, it seems compiler is intentionally silently disregarding the override keyword, so that you can have imported files overriding other files, yet still working on their own. So. closing this one then.
