### ISSUE TITLE
Code works on Kontakt but won't compile

### ISSUE THREAD

**Issue by gabrieldib** [nojanath/SublimeKSP#222]
When using this code:

```
on init 
    declare ui_slider $my_knob1(1,1000000)
    declare const $MY_KNOB1_DISP := get_ui_id($my_knob1)
end on
```

I get the error: "Expression uses non-constant values or constant variables"

However, Kontakt compiles the code above and runs it.

**Comment by mkruselj** [comment]
This is due to Extra syntax checks option. Needs investigation.
