### ISSUE TITLE
Passing a string with commas as a macro argument confuses the parser

### ISSUE THREAD

**Issue by jtackaberry** [nojanath/SublimeKSP#23]
If you have a macro that accepts an argument that's used as a string and then pass a string containing a comma, the parser confuses the commas as separate arguments and complains about incorrect number of arguments.

Test case:

```
macro test(msg)
    message(msg)
end macro

test("this, breaks, the, parser")
```

Functions don't have this problem, and in fact can mask the macro issue through indirection:

```
macro _test(msg)
    message(msg)
end macro

function test(msg)
    _test(msg)
end function

test("this, works, fine")
```

**Comment by neblix** [comment]
Yes, we've had this problem in the past. I confirm this issue.

**Comment by andreasOL16** [comment]
Hmmm...works for me without problems...

**Comment by SamWindell** [comment]
It seems to work okay for me at the moment, but I believe you that this is sometimes an issue. At the beginning of the compiling process all strings in the script stored and each string is replaced with a number so that they can be put back in further down the process.

I'm not sure on the exact circumstances, but I think these string placeholders are sometimes not made. This could be why the comma in strings work correct only sometimes. I will have look about fixing this.

**Comment by neblix** [comment]
I don't know if it helps, but for us it always happened because we used a macro that did a control declaration and help text in one go. Whenever we put commas in the string for the help text argument, it would break:

```
macro ui.slider(#name#

end macro
ui.slider(VOLUME, 0, 1000000, "This slider is so cool, it doesn't even need a callback!", 500000)
```

**Comment by jtackaberry** [comment]
> the "control -> par := value" functionality is AWESOME!

Oh, awesome indeed!  I didn't even know about this.  I looked again at the documentation and couldn't find it mentioned anywhere.  There's one snippet of code in the section about multidimensional UI arrays that quietly uses this syntax and I missed it.

Maybe I'm blind. :)

**Comment by SamWindell** [comment]
> the "control -> par := value" functionality is AWESOME!

It is great! This is from Nils' features, but I don't believe it is documented anywhere. I'll quickly add it to the wiki.

**Comment by andreasOL16** [comment]
You find it documented in

http://nilsliberg.se/ksp/history.txt

Search for "Added new control parameter access feature (see example 3)"

**Comment by pryzmusic** [comment]
Fixed in the latest feature merge
