### ISSUE TITLE
Issue with async IDs and effect changes

### ISSUE THREAD

**Issue by dxmachina** [nojanath/SublimeKSP#24]
The following code is currently not compiling using your latest version (but does work in KT):

```
on init
	declare ui_button $loadAChorus
	declare $LOAD_ID
end on

on ui_control($loadAChorus)
	$LOAD_ID := set_engine_par($ENGINE_PAR_EFFECT_TYPE, $EFFECT_TYPE_CHORUS, -1, 0, $NI_BUS_OFFSET)
end on

on async_complete
	if ($NI_ASYNC_ID = $LOAD_ID)
		message($NI_ASYNC_EXIT_STATUS)
	end if
end on
```

I believe the issue is the actual async assignment to the set_engine_par being rejected.

Thanks.

**Comment by SamWindell** [comment]
Thanks for the example. I can't seem to reproduce this, it seems to compile fine here. Do you perhaps still have the old version active somehow, as well as the new version?

**Comment by dxmachina** [comment]
Reinstall + clearing of cache seems to have fixed it. Thanks and sorry for the trouble.
