### ISSUE TITLE
strange compile behavior with macro

### ISSUE THREAD

**Issue by gabrieldib** [nojanath/SublimeKSP#269]
please look at the screen shots.
the first one compiles, the next 3 do not. and I have not idea why, because the error window from the plugin only points to a line that has nothing to do with this code (a comment) and has no error messages. 

<img width="1261" alt="compiles" src="https://user-images.githubusercontent.com/31329383/209013420-04e32481-785b-44c1-9870-b3ab4737d2d2.png">
<img width="1235" alt="does not compile 1" src="https://user-images.githubusercontent.com/31329383/209013425-0a407750-5ac3-4eee-bc20-edeafe8ef033.png">
<img width="1248" alt="does not compile2" src="https://user-images.githubusercontent.com/31329383/209013429-4854ad7b-6eb0-42cb-a25c-12d1d1263e84.png">
<img width="1253" alt="does not compile3" src="https://user-images.githubusercontent.com/31329383/209013431-d4a77112-006f-4dda-8cd7-c1914e6e3562.png">

**Comment by mkruselj** [comment]
We can close this one now, since the issue was that not closed {} comment inside a // comment, right @gabrieldib?

**Comment by mkruselj** [comment]
Closing this one after all. If you think this was a mistake let me know, but IIRC the issue was sorted out by changing the comment type you had there.
