### ISSUE TITLE
Improve and add additional pragmas

### ISSUE THREAD

**Issue by JackWilliams-FractureSounds** [nojanath/SublimeKSP#275]
New pragmas:
 - combine callbacks
 - compact variables
 - optimize code
 - extra syntax checks
 
Improvements:
 - allow output source to compile to multiple output files

QoL Features (low priority):
- select folder from dialog and automatically add save_compile_source pragma

**Comment by gabrieldib** [comment]
please add the possibility to add multiple save_compile_source
this way we can have the compiled going into the /Resources/scripts folder AND a local copy inside the sources folder, to avoid having to copy the compiled code every time we need to check something.

**Comment by gabrieldib** [comment]
One more - have the option to preserve the spaces / tabs. Quite useful if you need to read the compiled code.

**Comment by JackWilliams-FractureSounds** [comment]
Closed as issue is already raised in #240
