### ISSUE TITLE
Typo in parameter name - possible bug

### ISSUE THREAD

**Issue by teskdop** [nojanath/SublimeKSP#276]
In ksp_compiler.py:
`self.traverse(ast, parent_funciton=None, function_params=[], parent_families=[])`
**parent_function** is spelt wrong and a search shows this is the only place it shows up with that spelling. I don't know python, but it seems like a bug to me so thought I should mention it.

**Comment by JackWilliams-FractureSounds** [comment]
Thanks teskdop! Good spot :))
