### ISSUE TITLE
Sublime 4 /KSP syntax auto-complete not working

### ISSUE THREAD

**Issue by flav1o5** [nojanath/SublimeKSP#278]
Hello,

The main issue here is that I don't get auto-complete in Sublime 4. Everything worked great 2-3 days ago though.

For example, the only thing that's shown for auto-complete is Koala snippets only. Anything else KSP-related is gone. 
I was wondering if there's a proper way to install this or if I'm missing something.

The problem persists after uninstalling and re-installing Sublime entirely and removing/adding the KSP package in Package Control.

Thanks in advance! @mkruselj

**Comment by JackWilliams-FractureSounds** [comment]
Hi @flav1o5, that's really odd, the update was supposed to add the autocompletes to ST4 :0

I presume you have, but just checking... After updating to ST4 and installing sKSP, did you restart ST? There's occasionally issues with initialising packages if ST remains open after install

**Comment by flav1o5** [comment]
Thanks for your prompt reply Jack!

Windows. The same problem emerged on my Mac too. 
Yes, I closed and reopened ST, and turned pc off / on. Also tried checking "Extra syntax checks" but no luck.
I will positively say that up until v4126 eveyrthing worked great,

**Comment by flav1o5** [comment]
This is how things look in ST3.

![7](https://user-images.githubusercontent.com/88741317/209548707-5d96ecdb-784b-49e5-a61b-cd5483740581.jpg)
![8](https://user-images.githubusercontent.com/88741317/209548711-ab07d7c2-3ef8-44b2-a56b-5bf20870e420.jpg)

**Comment by JackWilliams-FractureSounds** [comment]
Hey Flav1o5, thank you for these screenshots. Just to clarify, has the autocompletes ever worked in ST4 for you?

I'll investigate and see if other people have had this issue. If autocompletes are a major part of your workflow then for the time being I recommend you revert back to a version where they definitely worked for you, like ST3.

I will try and find a solution, but it'll be a little tricky if I can't recreate this, so please bear with! Perhaps we can develop a safety autocompletes system to make sure users can always access this feature.

All the best :)

**Comment by flav1o5** [comment]
3-4 days ago when I took a break from writing I was indeed working in ST4 (no blinking cursor).

Even built-in KSP variables worked by adding "$" before them. In ST3 they appear when no "$" is added.

Strangely though, Koala auto-complete did not work for me as of yesterday. Now basically I get only Koala auto-complete (which is great), but not KSP. I tried removing just Koala but it did not solve the problem.

Roles reversed somehow. 

Thanks, and Merry Christmas Jake!

**Comment by flav1o5** [comment]
I found where the issue begins. 

I opened ST4 on my secondary PC after probably 2 months. 
KSP syntax worked for 2 seconds, then text turned white to Plain Text, then back to KSP. After this, the same problem emerged. 

Most likely, the auto-update to the newest version of the KSP package is what takes out the auto-complete out of KSP for ST4.

**Comment by JackWilliams-FractureSounds** [comment]
But after restarting sublime text, this issue should have resolved itself :/

**Comment by flav1o5** [comment]
As a last effort, I've manually placed "Sublime-KSP" (release version 1.12.2) in the "Packages" folder and everything works fine again!

Version combo of **ST4 (4143)** and **SublimeKSP-1.12.2** seems to be it. 

You probably guessed I'm not an expert - haha. But I appreciate your help, Jake! And in general, the KSP package is such a time saver. Amazing stuff.

**Comment by JackWilliams-FractureSounds** [comment]
Hi Flav1o5, a small update!
I've realised that the fix I thought I was implementing has replaced the autocompletes with sublime snippets, rather than appending the autocomplete list! This is causing some of the previous autocompletes to be removed. I'm working on a solution as quickly as I can. Thank you for your input, I wouldn't have realised without your help!

**Comment by JackWilliams-FractureSounds** [comment]
Hey @flav1o5!
This all works correctly now, so just pull the latest version from the repo. Let me know if you have any issues :))

**Comment by flav1o5** [comment]
Hey Jack, 
In this one, I use the manually-placed KSP folder version 1.12.2
![Screenshot 2022-12-30 153347](https://user-images.githubusercontent.com/88741317/210075930-ed10c38b-425d-43fa-96d6-0071275e5627.jpg)
And this is after deleting the manual folder and installing KSP via Package Control
![Screenshot 2022-12-30 153515](https://user-images.githubusercontent.com/88741317/210075983-fd83ed0b-87c1-4f84-973c-92764eea9562.jpg)

No worries though, it might be something wrong on my end. I'll keep using version 1.12.2!

**Comment by JackWilliams-FractureSounds** [comment]
Hi @flav1o5,

If you download the latest version available here on the Git repo, the autocompletes should be fixed. Just place the new download in the same directory.

Make sure it's the latest commit, and not a release tag.

SKSP will be updated on Package control soon!

**Comment by flav1o5** [comment]
Hey Jack, 
I've tried it but it does not work. 
Absolutely no worries though, I'll try and keep things as they are which works perfectly!
Thanks and happy new year!
