### ISSUE TITLE
Combine duplicate callbacks - compile error when declaring a list

### ISSUE THREAD

**Issue by teskdop** [nojanath/SublimeKSP#279]
imported.ksp:
```
on init
    message("imported file")
end on
```
main.ksp:
```
import "imported.ksp"
on init
    declare list test[]
    list_add(test, 5)
    message(test[0])
end on
```
compile error: 
> list_add() can only be used in the init callback!

If the list is moved to the imported file, it will compile.
If import is commented-out, it will compile.
Also gives same error if both callbacks are in the same file.

Thanks for working on these updates.

**Comment by JackWilliams-FractureSounds** [comment]
Hi teskdop, thanks for highlighting this bug! I'll get this sorted asap!
