### ISSUE TITLE
Sublime Text 4 auto-complete - problem with UI control parameters

### ISSUE THREAD

**Issue by teskdop** [nojanath/SublimeKSP#287]
Sublime text 4 on Windows.
SublimeKSP 1.13.1.
Type: `icb + tab`
**init** callback created.
Type: `ui_switch + tab`
Switch declaration created.
Name switch **test_switch**.
Type: `test_switch -> w`
Get drop-down with while, whilec etc. but not width.

Remove 1.13.1 and replace with latest master with commit 9e4895f...
Re-start sublime text.
Repeat above and get the same result except no drop-down at all in last stage.

Went back and forth a couple of time between SublimeKSP versions to make sure.

Many thanks.

**Comment by JackWilliams-FractureSounds** [comment]
Hi Teskdop,
Thanks for making us aware of this issue, we will attempt to fix it soon!
