### ISSUE TITLE
Goto Definition Broken

### ISSUE THREAD

**Issue by JackWilliams-FractureSounds** [nojanath/SublimeKSP#289]
This is be because of index symbols.
![image-2.png](https://user-images.githubusercontent.com/88255410/210067896-22f919a3-6626-4893-a7ab-6a96f5b36db9.png)

(Removing them is is not a desired solution)

**Comment by mkruselj** [comment]
https://forum.sublimetext.com/t/goto-definition-breaks-when-symbol-added-to-index-lists/66565
