### ISSUE TITLE
define literals deprecated? Question on new usage

### ISSUE THREAD

**Issue by neblix** [nojanath/SublimeKSP#30]
I'm not quite certain how the new define functionality handles the old define literals usage case.

Before we had define literals such that I could write:

```
define literals names := (Bobby, Sam, Ashley)

macro doStuffOnPerson(#name#)
    message(#name#Slider)
end macro

literate_macro(doStuffOnPerson) on names

//compiles to

message(BobbySlider)
message(SamSlider)
message(AshleySlider)
```

How can I use the new define statement in this same way? It doesn't appear to document how, it simply says the old way (written above) is now deprecated. I would like to know because define literals is powering an important subcomponent of Super Audio Cart and I'd like to port it out of using deprecated features.

**Comment by SamWindell** [comment]
Apologies for the lack of clarity. There is an example in the literate_macros section of the added features wiki. Basically you can now just do this: 
```
define names := Bobby, Sam, Ashley
literate_macro(doStuffOnPerson) on names
```

**Comment by neblix** [comment]
Awesome! Thanks :)
