### ISSUE TITLE
Preprocessor issues when using files imported with namespaces

### ISSUE THREAD

**Issue by JackWilliams-FractureSounds** [nojanath/SublimeKSP#309]
Preprocessor variables are expected with namespaces, but have not been created. This applies to any preprocessors that use preprocessor variables (ui arrays, concat, lists). I think this issue is also linked to issue #208 

 ### Possible solutions
 - preprocessor variables are ignored when appending namespaces
 - create preprocessor variables for each namespace file

 ## Example
`main.ksp`
```
import "chord2.ksp" as Chordify
on init
	Chordify.on_init
end on
```
`chord2.ksp`
```
struct chord
   declare note[5] := (-1)
   declare @name := ""
   declare length := 3
   declare root := 0
   declare inversion := 0
   declare active := 0
   declare rootPosition := 0
   declare id := 0
end struct

macro on_init
   declare &chord chords_calc[6]
end macro
```
**Generates Error: **
![image](https://user-images.githubusercontent.com/88255410/215178988-6ec100b1-8656-4878-902e-76d3489c7a6d.png)

**Comment by mkruselj** [comment]
I'd recommend ignoring preprocessor variables when appending namespaces.
