### ISSUE TITLE
Add ParseException for unassigned const variables

### ISSUE THREAD

**Issue by JackWilliams-FractureSounds** [nojanath/SublimeKSP#331]
should be fix in `comp_extras.ASTVisitorCheckDeclarations`

```
on init
	declare const name
end on
```

**Comment by mkruselj** [comment]
Yeah there actually is a `raise ParseException` there but it's in the wrong place, it should be outside of the big if clause I think. But also that whole if clause `(if 'const' in node.modifiers:` seems quite a bit suspicious, I am not sure I can get any of those parse exceptions to show up by doing literal things those messages are reporting about...
