### ISSUE TITLE
Add get_ui_id() for -> shorthand when parent_panel

### ISSUE THREAD

**Issue by JackWilliams-FractureSounds** [nojanath/SublimeKSP#335]
`delay_settings_panel -> parent_panel := delay_panel`
Should compile to:
`set_control_par(get_ui_id(delay_settings_panel), CONTROL_PAR_PARENT_PANEL, get_ui_id(delay_settings))`

Currently not adding `get_ui_id()` for the last arg in `set_control_par`

**Comment by mkruselj** [comment]
Do we even have knowledge that `delay_settings` is a ui_panel, or is it just considered a variable internally?

**Comment by JackWilliams-FractureSounds** [comment]
Yes, sorry. so:
```
declare ui_panel delay_panel
declare ui_label delay_settings_label
delay_settings_panel -> parent_panel := delay_panel
```
