### ISSUE TITLE
Pinging Nojanath 

### ISSUE THREAD

**Issue by JackWilliams-FractureSounds** [nojanath/SublimeKSP#341]
Hi @nojanath,

My name is Jack, recently I've been contributing to this repo on a semi-regular basis alongside @mkruselj. I'm a big fan of the amount  of support this gives to KSP developers and want to enhance it any way I can.
Would it be possible to be added as a collaborator so I can contribute more freely and help keep the repo going?

All the best,
Jack

**Comment by nojanath** [comment]
Hi @JackWilliams-FractureSounds,

I'm happy to grant you contributor access. I'm thrilled to see this plugin keep improving.

Cheers,
JT

**Comment by JackWilliams-FractureSounds** [comment]
Thank you :)
