### ISSUE TITLE
Incorrect syntax highlighting when using brackets in function/macro argument list

### ISSUE THREAD

**Issue by SamWindell** [nojanath/SublimeKSP#35]
```
struct Point
    declare x
    declare y
end struct
define POINT(pointName) := pointName.x, pointName.y
macro addPoint(POINT(p1), POINT(p2))
    p1.x := p1.x + p2.x
    p1.y := p1.y + p2.y
end macro
```

This is purely an visual bug. The arguments to the macro `POINT(p1), POINT(p2)` are not correctly coloured.

**Comment by mkruselj** [comment]
Likewise, when using arrays within functions as arguments, square brackets aren't colored properly.

![brackets](https://cloud.githubusercontent.com/assets/2393720/20092986/0f471552-a59b-11e6-8f07-25ba573e8f6a.png)

**Comment by mkruselj** [comment]
OK I fixed this by changing the "Comma" match to this:

`    - match: "[,.()\\[\\]]"
      comment: Punctuation and brackets
      scope: punctuation`

**Comment by neblix** [comment]
Since Mario's syntax coloring changes are being imported into the main repository, I am closing this issue.
