### ISSUE TITLE
Define comma-separated auto-numbered constants

### ISSUE THREAD

**Issue by teskdop** [nojanath/SublimeKSP#354]
Something like this:
` define BD, RS, SD, HC, cHH, oHH`
Would be automatically numbed from zero like a const block but without having to be vertical and without having to use a prefix. A use case would be to put above arrays like this:
```
define          BD, RS, SD, HC, cHH, oHH
declare n[] := (36, 37, 38, 39,  42,  46) {note   }
declare c[] := (00, 01, 02, 03,  04,  04) {channel}
declare g[] := (00, 01, 04, 08,  12,  12) {group  }
declare r[] := (01, 01, 04, 04,  08,  08) {robin  }
```
This way when creating a project you can insert, cut or move a column from the array(s) and all the constants would be renumbered accordingly without having to maintain a separate set of defines and introducing bugs when you forget to update them.

**Comment by eitherys** [comment]
But why? This is trivial with existing features:

```
define DRUMS := BD, RS, SD, HC, cHH, oHH
on init
    literate_macro(declare const #l# := #n#) on DRUMS
end on
```

No prefixes (as it's not a const block but just regular const declares) and only one set.

**Comment by eitherys** [comment]
You can even create your own syntactic sugar for this:


```
define DRUMS := BD, RS, SD, HC, cHH, oHH
define Breakout := literate_macro(declare const #l# := #n#)

on init
	Breakout on DRUMS
end on
```

**Comment by mkruselj** [comment]
@eitherys' solution is quite elegant already, so I hope you don't mind if I close this issue as a won't do.
