### ISSUE TITLE
Function declarations do not accept args with dots in them

### ISSUE THREAD

**Issue by SamWindell** [nojanath/SublimeKSP#36]
```
function func(a.b)
    message(a.b)
end function
```

This will cause an error, while if you changed `a.b` to `a_b` it will work. This is really only a minor inconvenience at best. Fixing this will likely not be easy as it will involve diving into the workings of the parser.

**Comment by neblix** [comment]
I'm marking this as "wontfix" unless more people request it. It's kind of an extremely particular thing to do and bad coding practice in general, so only if more people are taken with the idea.
