### ISSUE TITLE
no shortcut (declare pers ...) for make_instr_persistent

### ISSUE THREAD

**Issue by andreasOL16** [nojanath/SublimeKSP#37]
Hello, one cannot declare an array of variables or gui elements that are instrument persistent rather than also snapshot persistent (if snapshots are enabled in the script). I would suggest an extension like

declare instr_pers ...
declare instr_read ...

best,
   Andreas

**Comment by SamWindell** [comment]
Good idea!

**Comment by neblix** [comment]
This will be supported in the latest update with the keyword `instpers`.
