### ISSUE TITLE
Allow combinable callbacks in macros

### ISSUE THREAD

**Issue by teskdop** [nojanath/SublimeKSP#378]
Now that we can combine callbacks, would it be possible to allow those inside macros like we can with ui_control() callbacks? Example:
```
on init
    CREATE_PGS(key_name, element_count)
end on

macro CREATE_PGS(key_name, element_count)
    // create key with matching persistent array...

    on persistence_changed
        // check persistence, update key with array...
    end on

    on pgs_changed
        // update array...
    end on
end macro

```
I'm sure it's a lot of time/work and probably not very high on the list if at all, but I mention it anyway just in case.
Close this if not likely to happen so it doesn't clog things up.

**Comment by mkruselj** [comment]
The above code wouldn't really work because macros inline in place, which means you would have created PCCB and PGSCB inside ICB, which is not allowed.
