### ISSUE TITLE
Add a .SIZE define for literal defines #416 is not working

### ISSUE THREAD

**Issue by blackeyedpony** [nojanath/SublimeKSP#426]
```
on init 

	define FOO := apple, banana, pear, kiwi
	message(FOO.SIZE)

end on
```
according to Add #416 this should print "4", right ? 

instead, the compiler throws:

_apple has not been declared! (line 10)_
_message(apple, banana, pear, kiwi.SIZE)_
_\<main script\>:6_

**Comment by mkruselj** [comment]
I think it's that define has to be used before it can be observed, perhaps?

**Comment by mkruselj** [comment]
Ah no, in this case it's actually incorrect definition, it should be:

```
on init 
    define FOO := "apple", "banana", "pear", "kiwi"
    message(FOO.SIZE)
end on
```

**Comment by mkruselj** [comment]
Ah no, this should still work for variables, too. It was my wrong assumption that we should only count the string replacement tokens (they are wrapped in squigglies). Instead, we should count commas in the definition of literate define. That should fix it!

**Comment by mkruselj** [comment]
Try now!
