### ISSUE TITLE
new "branch optimisation" breaks existing projects

### ISSUE THREAD

**Issue by blackeyedpony** [nojanath/SublimeKSP#436]
The new branch optimisation is more strict in regards to variable declaration order. 
Projects which worked fine before do find variable definitions now.
I didn't investigate much, but I assume that many other projects are affected. Any ideas ?

https://github.com/nojanath/SublimeKSP/commit/e58deda6196b1794e0ad0a31025935d5261f3f80

**Comment by mkruselj** [comment]
#437 should fix it

**Comment by blackeyedpony** [comment]
yep, #437 works for me. Thanks Mario.
