### ISSUE TITLE
Type casting issue: script runs in Kontakt 7 but fails to compile in Sublime KSP

### ISSUE THREAD

**Issue by raptor-666** [nojanath/SublimeKSP#456]
There is a discrepancy between the way a script is handled in the Sublime KSP package and in Kontakt 7's script editor. The provided script runs without issues in Kontakt 7 but throws an error during compilation in Sublime KSP.

**Steps to Reproduce**
1. Create a new KSP script with the following code
```
on init
    declare ~var := -1.0
    message(int(sgn(~var) * 1000.0))
end on
```
2. Compile the script.

**Screenshot**
![image](https://github.com/nojanath/SublimeKSP/assets/32146190/b89dae80-8572-4e5b-9d84-183832b8870a)

**Comment by mkruselj** [comment]
OK yeah this is a bit tricky, because sgn() (and signbit(), by extension) are overloaded in KSP to support integers and reals at once, but in sKSP they are made to return integer always, and this trips up the compiler...

**Comment by mkruselj** [comment]
I have a solution I think. abs() already has special handling for this, so it's a matter of appending these functions in that place, too :)

**Comment by mkruselj** [comment]
@raptor-666 Try pulling the master branch and check it out 🙂
