### ISSUE TITLE
 f-string fails on shorthand "->" expressions

### ISSUE THREAD

**Issue by blackeyedpony** [nojanath/SublimeKSP#462]
It would be nice if you could get this to work:

```
on init 
	declare ui_slider sl (0, 100)
	message(f'test slider value: <sl -> value>')
end on
```
the precompiler fails to recognise the "->" keyword and stops the variable insertion at the first found ">" and logically comes up with: message("test slider value: " & sl - & " value>")
Could you try changing the insertion regex to span to [^-]> ?

**Comment by mkruselj** [comment]
Regex is not used for f-strings, as I was told by @eitherys..

**Comment by mkruselj** [comment]
@blackeyedpony There will be a fix for this but you will have to escape the `>` character inside the outer `<>` brackets,  so instead of `->` it will have to be `-\>`.

**Comment by blackeyedpony** [comment]
ah ok. I didn't look at your code yet. 
Nevertheless, the string formatting  is a very handy addition, thanks Mario!

**Comment by mkruselj** [comment]
All the thanks goes to @eitherys who actually coded it :)

**Comment by eitherys** [comment]
This was fixed but that commit contained an error I didn't test; a new commit is on the way that also adds support explicitly for `->` without the use of an escape. So your original code compiles now on my end.

**Comment by eitherys** [comment]
![image](https://github.com/user-attachments/assets/7611fe3b-158c-4409-84c3-fdceddff80d6)
