### ISSUE TITLE
"declare ui_xy ?my_xy[4]" not working

### ISSUE THREAD

**Issue by drumasonicDaniel** [nojanath/SublimeKSP#47]
The compiler says "Syntax error" when using the command
declare ui_xy ?my_xy[4]

Latest version of Kontakt, 5.6.5

**Comment by blackeyedpony** [comment]
yes, please add the new xy ui_control to the compiler.

**Comment by SamWindell** [comment]
Just created a pull request that fixes this. You can download the fixed version manually if you want it now from my fork: https://github.com/SamWindell/SublimeKSP

#48

**Comment by nojanath** [comment]
Nice Sam.  Just merged the PR and it will be in package control shortly.

**Comment by SamWindell** [comment]
I think ui_xy is still not working correctly. I opened a new issue, but I think it's the actually the same problem as this. 
#49

**Comment by blackeyedpony** [comment]
It's not working at all for me. Entering these lines 

	declare ui_xy ?my_xy[2]
	set_control_par(get_ui_id(my_xy),CONTROL_PAR_MOUSE_BEHAVIOUR_X,300)

results in:

```
{ Compiled on Fri Jan 13 15:31:05 2017 }
on init
  declare %my_xy[2]
  declare ui_xy $my_xy0
  %my_xy[0] := get_ui_id($my_xy0)
  declare ui_xy $my_xy1
  %my_xy[1] := get_ui_id($my_xy1)
  set_control_par(get_ui_id(%my_xy),$CONTROL_PAR_MOUSE_BEHAVIOUR_X,300)
end on

```
So the interpreting goes wrong in several places.

**Comment by SamWindell** [comment]
#50
