### ISSUE TITLE
Const symbols in 5.6.5

### ISSUE THREAD

**Issue by SamWindell** [nojanath/SublimeKSP#51]
```
on init
    declare const ~PI := ~NI_MATH_PI
end on
```

This doesn't work. This problem is deeper down in the compiler and it's probably best to wait for Nils to release his next official version.

**Comment by neblix** [comment]
Hey Sam,

We've noticed this too. I have a couple hypotheses on what may be causing this and I plan to take a look relatively soon.

**Comment by mkruselj** [comment]
This seems to be fixed in 1.9.2 now!
