### ISSUE TITLE
ui_xy not working

### ISSUE THREAD

**Issue by magneto538** [nojanath/SublimeKSP#52]
` declare ui_xy ?myXY[4]`

This does not work. A syntax error is returned. Are there any news about an official release for Kontakt 5.6.5?

**Comment by SamWindell** [comment]
I'm afraid I can't help with full support for 5.6.5, but I did make XY pads work a while back: #50 
It is part of this repo if you want to manually download it, and check it is working for you? 

I'm not sure if this change has made it to package control yet? @nojanath

**Comment by magneto538** [comment]
I checked the repo and it appears that a commit was issued on Jan 14th which appears to have this fix (at least that's what the changelog says), but the latest Release is dated Oct 22nd. A new release is needed to push the updated package to PackageControl. Testing this commit now.

**Comment by magneto538** [comment]
Ok, [this](https://github.com/nojanath/SublimeKSP/tree/69791a99abe941564859b58b2084e978a42e48c0) is the version that seems to be working. It's the latest one, but like I said it's not on PackageControl yet.

**Comment by nojanath** [comment]
Strange, I'll figure out why that didn't make it to Package Control and get that fixed.

**Comment by nojanath** [comment]
@magneto538 @SamWindell Fixed.  I forgot to push the tag...

It should be available in Package Control soon.

**Comment by nojanath** [comment]
Marking as closed.
