### ISSUE TITLE
Simplified syntax and ui_xy

### ISSUE THREAD

**Issue by magneto538** [nojanath/SublimeKSP#53]
The simplified syntax `ui_ctrl -> cursor_picture := "picture_name"` doesn't work. 

Actually, this syntax is missing a parameter in order to be used correctly, as `CONTROL_PAR_CURSOR_PICTURE` uses the new `set_control_par_str_arr` to work: this function needs to be fed with an additional parameter which is the index of the string array in question (page 120 on KSP manual).

The output of this should be 
`set_control_par_str_arr( get_ui_id(?ui_ctrl), $CONTROL_PAR_CURSOR_PICTURE, "picture_name", ???idx???)`
while at the moment it is 
`set_control_par( get_ui_id(?ui_ctrl), $CONTROL_PAR_CURSOR_PICTURE, ...)`

**Comment by neblix** [comment]
I think the best thing is to pull support for using the magic control par `->` on this parameter until a future time when we find a way to define syntax for providing that extra argument.

**Comment by mkruselj** [comment]
I don't think there's an eeasy way to support `_arr` variant with `->` shorthand...

**Comment by mkruselj** [comment]
After looking at it more, this is really as good as it gets. Closing.
