### ISSUE TITLE
XOR operator

### ISSUE THREAD

**Issue by magneto538** [nojanath/SublimeKSP#55]
When I type `.xor.`, SublimeKSP highlights it as if it was an actual operator, but Kontakt does not support it, thus the compilation fails.

Might be a good idea to add the operator to the compiler so that if I write `.xor.` it would be compiled as `.and. .not.` (which is exactly the same thing).

**Comment by andreasOL16** [comment]
hmm...

a|b|a .xor. b|a .and. .not. b
-|-|-|-
0|0|0|0
0|1|1|0
1|0|1|1
1|1|0|0

**Comment by magneto538** [comment]
What about:

.not. (a .and. b)

**Comment by andreasOL16** [comment]
a|b|a .and. b|.not. (a .and. b)
-|-|-|-
0|0|0|1
0|1|0|1
1|0|0|1
1|1|1|0

Well, this too trivial for a guessing game :-) There are a few ways to synthesize xor, depending on what elements you have (if you were to assemble it in hardware with logic circuits). but of other logic function (.and. or .or.) and an inverter is too little. Just write down the truth table and check

**Comment by magneto538** [comment]
Here we go.

(a .and. .not. b) .or. (.not. a .and. b)

|	a 	|	b	|	a .and. .not. b	|	.not. a .and. b	|	... .or. ...	|
|-------|-------|-------------------|-------------------|-------------------|
|	0	|	0	|			0		|			0		|			0		|
|	0	|	1	|			0		|			1		|			1		|
|	1	|	0	|			1		|			0		|			1		|
|	1	|	1	|			0		|			0		|			0		|

**Comment by andreasOL16** [comment]
Right, this is one variant that works. As far as I have seen you need three logic functions to simulate .xor. (here: two .and. and one .or.) plus negations.

**Comment by magneto538** [comment]
Yep. All the operations in Boolean algebra are based on AND, OR and NOT, so any advanced operation (such as XOR) is based entirely on combinations of these three operators.

**Comment by clearfrost** [comment]
Just wanted to add that in Big Bob's maths library he has an XOR function which returns the equivalent of:
(a .or. b) - (a .and. b)

**Comment by mkruselj** [comment]
It would actually be better if Kontakt supported it in the first place. 🙂

**Comment by mkruselj** [comment]
Coming natively to Kontakt relatively soon. 🙂
