### ISSUE TITLE
Add syntactic sugar for binary numbers

### ISSUE THREAD

**Issue by mkruselj** [nojanath/SublimeKSP#57]
This would be SO useful!

Something like `0100101011b` would compile to 299 in base 10.

Should be pretty easy to add? Benefits are quite obvious, I would say :)

**Comment by magneto538** [comment]
Big quote for Mario. I'm seeing a lot of applications when dealing with bitmasks.

**Comment by neblix** [comment]
Done. Will show up in next release.

The new syntax is as follows:
```
b1110, LSB-left, compiles to 7
1110b, LSB-right, compiles to 14 (this is the standard one most people think of)```
