### ISSUE TITLE
Missing get_key_type and load_array snippets

### ISSUE THREAD

**Issue by magneto538** [nojanath/SublimeKSP#61]
See above.

BTW...
Is someone still taking care of this fork of SublimeKSP? We haven't seen updates in a while now. Most of our work is based on this compiler, so it'd be amazing if you guys could tell us if this project is still on or not 😃

**Comment by SamWindell** [comment]
I'm afraid my Kontakt days are past me. I tend to keep an eye on this repo though. If anyone would like to have a look at further developing it I will be happy to point them in the right direction (regarding the bits that I have worked on, I don't know much about a lot of Nils's work). I had never used python before this project, if that is any measure of its complexity.

**Comment by neblix** [comment]
We don't use snippets for normal functions, but I'll make sure the autocomplete always runs.
