### ISSUE TITLE
mf_set_export_area error

### ISSUE THREAD

**Issue by gh54** [nojanath/SublimeKSP#62]
In ksp_builtins_data.py:
mf_set_export_area(<name>,<start-pos>,<end-pos>,<start-track>,<end-track>):integer

a) message(mf_set_export_area("name",-1,-1,-1,-1))
compiles without error
b) area_status := mf_set_export_area("name",-1,-1,-1,-1)
compilation aborts with error message "Expected expression of integer type, got None.
c) in case of an error (b) the reported error line is sometimes wrong (pointing to the prev. line).

**Comment by neblix** [comment]
This has been fixed in pull request #66
