### ISSUE TITLE
VERY bad bug with multi-dimensional arrays

### ISSUE THREAD

**Issue by magneto538** [nojanath/SublimeKSP#63]
It seems that we cannot set multi-dimensional arrays as persistent!

Whenever I try to set a multi-dim array as persistent using the syntax `array[5, 7]`, the following error is returned:

```
Wrong number of parameters to array.get. Expected 2, got 0. (line xxx)
make_persistent(array)
```

This is a very bad bug, effectively limiting the usability of multi-dim arrays.

**Comment by SamWindell** [comment]
Could you be exact with the error? `declare pers foo[2, 2]` works fine over here.

**Comment by magneto538** [comment]
Oh right - I forgot about the "pers" thing. I was trying to use the standard `make_persistent()` function, which does in fact return the error. Works fine with "pers".
