### ISSUE TITLE
Multi-dim arrays

### ISSUE THREAD

**Issue by magneto538** [nojanath/SublimeKSP#64]
Hey folks,
After shedding some light on the `pers` thing for multi-dimensional arrays, I hope you will give me feedback this matter too.

```
on init
	declare foo[2, 5]
	load_array(foo, 1)
end on 
```

I'm getting this error:

> Wrong number of parameters to foo.get. Expected 2, got 0. (line 16)
> load_array(foo, 1)
> 
> <main script>:3

**Comment by SamWindell** [comment]
You need to prefix the name with a underscore for something like this. load_array(_foo, 1)

Let me give some backstory for if anyone is interested. Multi-dim arrays are a wrapper for a property - a feature Nils implemented. When you declare a multi dim array, behind the scenes there is a normal array created that is a the size of all the dimensions multiplied together. This array is given the same name but with an underscore, for your example _foo. Then there is a property created with name given (foo), the property requires you give it arguments 2 for a 2d array, 3 for 3d array, etc. So when you need to access an element of the multi-dim array use the normal name, and when you need to access the array as a whole (or just want to use the 1d version) use the underscored name.

**Comment by magneto538** [comment]
Oh I see! Thanks a lot!
Perhaps this might be added to the Wiki.

**Comment by SamWindell** [comment]
Sure, I have added a little more to the wiki.

**Comment by neblix** [comment]
Since this has been resolved, I am closing.
