### ISSUE TITLE
Transfer/Grant Access Rights for Repository?

### ISSUE THREAD

**Issue by neblix** [nojanath/SublimeKSP#67]
Hey,

I'm thinking since this isn't seeing any activity, for the future of this plugin it would be good to have someone who's still active in Kontakt development to have access to pushing out updates via this repository to package control. It's not just about feature additions, but also keeping up with new KSP syntax including new engine par constants. The latter is a baseline requirement, and we can not develop for new Kontakt versions if the SublimeKSP plugin fails compilation on undefined builtin constants.

I would like to volunteer myself, since I have a working knowledge of how to manage git version control and branching, 2 years of extensive experience in advanced KSP (I'm the Software Architect at Impact Soundworks) as well as an advanced understanding of python, and ideas for many cool features to improve the SublimeKSP experience. I studied computer science courses in school and having a working knowledge of the concepts in abstract models and expression parsing. I'm also in close contact with EvilDragon, who has provided already many helpful modifications to continue keeping the plugin up to date, and also has ideas for things he'd like to see in the plugin.

**Comment by nojanath** [comment]
Hi @neblix,

Thanks so much for volunteering to take this over.  Other projects have taken priority over my KSP work and Sam has moved on as well.  My original plan for this repo was to make installing Nils' plugin easier and Sam provided some amazing additions.  I'd love to see work continue on what he has added.

I'm happy to give you collaborator access.  I'm sure it will be in great hands.

Cheers,

JT

**Comment by neblix** [comment]
Thanks so much!

If possible, could you give an overview of the process of pushing updates to package control? Obviously I will be very careful and diligent in making sure updates are secure and compatible. I just would like to know how the process works.

**Comment by nojanath** [comment]
Absolutely.  It's quite simple.

* Update messages.json with the latest version number, e.g. 1.5.2, and a link to the matching "messages" file.  There are examples in the file to copy.
* Create the messages/1.5.2.txt file to function as a Readme when the plugin auto updates.
* Create a git tag that matches that version number.
* Push the tag to the repo.
* Wait about an hour.
* Profit.

**Comment by neblix** [comment]
Wonderful. Thank you. I've processed the pull request for the 5.7 update and will probably send out a release later today.

**Comment by magneto538** [comment]
@neblix IOn case you need further help with pushing stuff to PackageControl, I've been using it for Koala for quite some time now, so I'd be glad to help (although it's really simple so I don't think you'll encounter any issues)
