### ISSUE TITLE
'list' can't be used in if statements

### ISSUE THREAD

**Issue by magneto538** [nojanath/SublimeKSP#70]
...which is OK I guess, but this means it can't be used in `if 1=1` trick in the init callback. Pretty annoying sometimes, especially if you want to keep your code well organised. Is there any reason why we can't use it in if statements?

**Comment by neblix** [comment]
I wouldn't know off the top of my head but since this wasn't an original Nils feature, I imagine it's not too deeply embedded that it can't be changed.

**Comment by magneto538** [comment]
Yeah sure. I just can't think of a scenario where we shouldn't be able to use a list into an if statement. Kontakt allows us to declare variables inside ifs and loops (although any condition will be ignored anyways as far as I remember), so I don't think it has anything to do with Kontakt's parser. Maybe I'm missing something.
