### ISSUE TITLE
"MOD" can no longer be used as a variable name

### ISSUE THREAD

**Issue by blackeyedpony** [nojanath/SublimeKSP#73]
1.6.1 breaks ksp code containing the variable name "MOD" which previously compiled without error.
```
on init 
	family MOD
		declare test	
	end family
	declare MOD := 1
end on
```

**Comment by neblix** [comment]
Hi,

It appears there's a hasty parsing of case-insensitive keywords in the compiler that make it recognize MOD as the "mod" keyword. I had no idea it would hastily look for keywords despite the context they appear in (`declare MOD` should be immediately parsed as `declare $MOD`), and it seems like this is a compiler design flaw I didn't foresee when I had altered the parsing code to add binary numbers (for some reason, the "mod" keyword is handled in the same location).

I will have this released today as a hotfix 1.6.1.1.

**Comment by neblix** [comment]
I have fixed this in 34b12a6.

**Comment by blackeyedpony** [comment]
Thanks 👍

**Comment by neblix** [comment]
Sorry, this was supposed to be released days ago. For some reason the 1.6.1.1 tag didn't go through. I'm re-doing it on 1.6.2 now.

**Comment by magneto538** [comment]
PackageControl only supports tags with three values as far as I know. I had
the same issue a while ago.

**Comment by neblix** [comment]
How cumbersome!

In any case, this is done.
