### ISSUE TITLE
multi-thread support

### ISSUE THREAD

**Issue by Levitanus** [nojanath/SublimeKSP#75]
I've noticed, that compilation takes only one thread, and while i'm using some "dirty" things like iterations on maximum, than minimising them with define-based conditions - compilation can takes long. Is it possible to run compilation on the more than one theads? I've google'd qickly, and find, that it's solving on the plugin code level, so, afraid, can't make anything from my side :(

**Comment by neblix** [comment]
Compilation can not be done in parallel as it needs to sequentially pass over the code in stages. These can not be done asynchronously.
