### ISSUE TITLE
self-made classes for the compiller

### ISSUE THREAD

**Issue by Levitanus** [nojanath/SublimeKSP#76]
I've asked this by official e-mail, but have not received the answer so if this is not correct question, I'm sorry.
Is structure of text "input" of the compiler similar to the self.view class of ST? How can i "plug" into the text buffer of the compiler? Can i basicly replace the self.view to something else as the start point?

**Comment by neblix** [comment]
Refer to ksp_plugin.py on the usage of the KSPCompiler python class.

It is far too complicated to casually advise people on how to implement their own platform for using the compiler. It was not designed by Nils in a modular fashion and relies on much of Sublime's facilities to work as intended.
