### ISSUE TITLE
How to use compiler with another editor?

### ISSUE THREAD

**Issue by AlesTsurko** [nojanath/SublimeKSP#79]
Hi,
I'm a Vim user and would like to use this awesome preprocessor in my editor. How can I do it? Or maybe it's possible to compile via command line?

**Comment by neblix** [comment]
The compiler is not designed for any usage besides with Sublime. If you would like, you can look at the sublimeksp plugin file in the root level of the repository and examine how it is invoked using python and supplying various option arguments. 

You can attempt to write a python script to simulate the usage of the compiler, and then supply a file name argument at the command line level to the script.

**Comment by AlesTsurko** [comment]
Thanks.

**Comment by AlesTsurko** [comment]
@neblix Following your advice, I just find out that it's already working as a standalone compiler and has extra arguments! ```ksp_compiler3/ksp_compiler.py``` is the entry point. Just needed to install ```ply```, and comment the line ```import ksp_compiler``` in the ```preprocessor_plugins.py```. Then ```python ksp_compiler.py -h``` gives output:
```
usage: ksp_compiler.py [-h] [--compact] [--compact_variables]
                       [--extra_syntax_checks] [--optimize]
                       source_file [output_file]

positional arguments:
  source_file
  output_file

optional arguments:
  -h, --help            show this help message and exit
  --compact             minimize whitespace in compiled code
  --compact_variables   shorten and obfuscate variable names
  --extra_syntax_checks
  --optimize            optimize the generated code
```

And ```python ksp_compiler.py input.ksp output.ksp``` succesfuly compiles the script.

It would be nice to add documentation on this.
