### ISSUE TITLE
Sublime Text -  "callbacks & functions" or "ksp reference" in any side like "Kscript Editor" (more important for workflow)

### ISSUE THREAD

**Issue by aviramdayan** [nojanath/SublimeKSP#84]
Need to add like "Kscript Editor"

**Comment by mkruselj** [comment]
It's probably best to just have KSP reference PDF open at all times.

**Comment by mkruselj** [comment]
It won't happen in SublimeKSP because extensions cannot add side panes in Sublime. KScript Editor is severely outdated by now (both its command reference, and support for newer KSP and compiler functionality) and it is really not advised to use it.

**Comment by aviramdayan** [comment]
I would say that the window of "callbacks & functions" in "Kscript Editor"
more important for workflow

in Sublime Text - Ctrl+R Show the "callbacks & functions"
but it's not a practical way

I will probably continue to work with "Kscript Editor"
And sometimes just check what's new in "callbacks & functions"

tnx mario

**Comment by mkruselj** [comment]
Well, suit yourself, but you're missing out on a lot.
