### ISSUE TITLE
const arrays removed from compile

### ISSUE THREAD

**Issue by ghost** [nojanath/SublimeKSP#86]
Hello,
This code compiles:
```
on init
	declare const TEST_ARRAY[3] := (0, 1, 2)
	declare ui_switch test_switch
end on
on ui_control(test_switch)
	message(TEST_ARRAY[1])
end on
```

but results in:
```
on init
  declare ui_switch $test_switch
end on

on ui_control($test_switch)
  message(%TEST_ARRAY[1])
end on
```
Sorry if it's already known about.

**Comment by blackeyedpony** [comment]
Yes, the compiler should assert when declaring a const array. 
Nevertheless, KONTAKT will not parse a script declaring const arrays as KSP is only capable of handling integers as constant.

**Comment by royalbox** [comment]
Thanks or the reply.
If you're importing the script into Kontakt from the resource folder rather than the script editor and pressing the '!' reload button to see changes, then you won't see the error, so it would be best if the compiler caught it first.
Thanks again.

**Comment by mkruselj** [comment]
Why even use `const` in the above example? It's completely unnecessary.

**Comment by mkruselj** [comment]
At last managed to figure out how to guard against this, although I could only have it with Extra syntax checks option enabled. Still, next update will have compiler raise exception if somebody tries to declare a const array. 🙂
