### ISSUE TITLE
Enable 'define' literal macros to be unrolled as separate constants in constant blocks

### ISSUE THREAD

**Issue by magneto538** [nojanath/SublimeKSP#88]
It'd be amazing if something like this:
```
define NAMES_MACRO	:= name_1, name_2, name_3

const CONST_LIST
	NAMES_MACRO
end const
```
could be read by the compiler like this:
```
define NAMES_MACRO	:= name_1, name_2, name_3

const CONST_LIST
	name_1
	name_2
	name_3
end const
```
and then compiled accordingly. Perhaps there is already a way to declare a set of constants given a `define` literal macro, but I'm not aware of it.

**Comment by magneto538** [comment]
To be fair, there is a pretty quick workaround, but it's not exactly the greatest one as for the readability of the script. 
Instead of using constant blocks, I am using literate_macro and the automatic increment feature built in SublimeKSP:
```
START_INC(N, 0, 1)
literate_macro(declare const CONST_LIST.#l# := N) on NAMES_MACRO 
END_INC
```
This works, although it's not exactly what I refer to when speaking of 'nice coding'...

**Comment by mkruselj** [comment]
KSP is not "nice coding" any way you turn... :P

**Comment by mkruselj** [comment]
Defines are processed before const blocks, which makes this particular issue a really hairy one to resolve. Plus, workaround exists, so closing this one.
