### ISSUE TITLE
Control families and matrix bug?

### ISSUE THREAD

**Issue by magneto538** [nojanath/SublimeKSP#91]
```
on init 
	family UI 
		declare some_array[2, 200]			
	end family
end on 

on persistence_changed 
	load_array(_UI.some_array, 1)
end on
```

This wouldn't compile. The compiler returns "_UI.some_array has not been declared! (line 21)
load_array(_UI.some_array, 1)"

Probably there is a correct syntax to make this work, but I'm not sure what it should be. Hints?

**Comment by blackeyedpony** [comment]
What about ?
load_array(UI._some_array, 1)

**Comment by magneto538** [comment]
Correct. I could've checked the compiled output before posting this tbh. Seems a bit not intuitive, but works.

**Comment by blackeyedpony** [comment]
No prob. Keep up the great work on Koala :)
