### ISSUE TITLE
Autocomplete not working with strings starting with "$"

### ISSUE THREAD

**Issue by highvoltaged** [nojanath/SublimeKSP#94]
Autocomplete with TAB, ENTER, or CTRL+SPACE will delete any string that starts with a $ character after it offers to autocomplete.

REPRODUCE:
write $whatever
press enter
start to write $whate[TAB]
it offers to autocomplete, and then it just deletes the string. No matter what key i press (ENTER, TAB)

gif:
https://www.dropbox.com/s/fqsmiyye0jlcn43/sublime%20KSP.gif?dl=0

**Comment by magneto538** [comment]
Actually you’d want to leave $ out of the equation, as the compiler will add them regardless. Any particular reason why you are typing $ anyways?

**Comment by highvoltaged** [comment]
Wait, i was under the impression that it's the only way to declare knobs, variables, and most of Kontakt Script's functions.  I didn't know that i don't actually have to use them.  Thanks.

But anyway isn't that a bug?

**Comment by magneto538** [comment]
You can leave $ and % out when using SublimeKSP as they will be added upon compiling the script. You have to use @, !, ~ and ? for string and real arrays anyways.

Yep, looks like a bug :)

**Comment by highvoltaged** [comment]
Just tried it... Oh this relieves me from a lot of headache actually. I'm not married to the $ sign :D

**Comment by mkruselj** [comment]
>  You have to use @, !, ~ and ? for string and real arrays anyways.

ONLY when declaring them. When referencing them, you don't need to use them at all (unless you have variables of different types with same names, like `!var` and `?var` and `%var` and `$var`, but that's not a nice thing to do :).

**Comment by pryzmusic** [comment]
Fixed in 1.9.2!
