### ISSUE TITLE
String matrixes not affected by preserve_names?

### ISSUE THREAD

**Issue by magneto538** [nojanath/SublimeKSP#96]
I have a string matrix declared using a Family:

```
family UI
	declare !pic[9, 9]
end family
```

I want to make this array's name preserved when compiling with 'Compact variables' option turned on. I've tried many different options:

```
{#pragma preserve_names UI__pic}
{#pragma preserve_names !UI__pic}
{#pragma preserve_names !UI.pic}
{#pragma preserve_names UI__pic}
```

None of these works. Note that this array, when saved to disk, is named `UI__pic.nka`. Is there a specific naming for this kind of situation?

**Comment by mkruselj** [comment]
Hm, `preserve_names UI.pic` works if you don't use a multidimensional array.

**Comment by blackeyedpony** [comment]
Did you try this options ?
{#pragma preserve_names UI._pic}
{#pragma preserve_names UI___pic}

3 underscores seem to be necessary as the underlying matrix array "_pic" creates one underscore and the dot conversion results in another 2.
```
{#pragma preserve_names UI._pic}

on init 
	family UI
		declare !pic[9, 9]
		UI.pic[1,1] := "Test"
	end family
	declare var
	var := 1
end on

{ Compiled on Fri Apr 20 09:53:02 2018 }
on init
  declare !UI___pic[81]
  !UI___pic[10] := "Test"
  declare $j511g
  $j511g := 1
end on
```
