### ISSUE TITLE
A way to retrieve the amount of entries in a literal define?

### ISSUE THREAD

**Issue by magneto538** [nojanath/SublimeKSP#99]
`define LITERALS := hello, world`

We can use literals `define` and then run `literate_macro` to unroll each literal to a specific operation. Would it make any sense to have the ability to retrieve how many string entries are in a define? Of course you may do that by declaring another define with the amount of entries, but I've found myself needing this when working on big, reusable code where you want to be able to change as little values as possible. Does this make any sense?

**Comment by neblix** [comment]
Yes, I think it would be easy to add an extra define constant automatically such as `LITERALS.GET_LENGTH`.

I also wanted a way of manually indexing them like `LITERALS[0]` but that would take a bit more work.
